# Generated by Django 3.1.4 on 2021-01-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('difficulty', models.IntegerField()),
                ('link', models.CharField(max_length=255, unique=True)),
                ('progressionTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exercises.exercise')),
            ],
        ),
    ]
