# Generated by Django 3.1.4 on 2021-01-29 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='progressionTo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Exercises.exercise'),
        ),
    ]
