# Generated by Django 3.1.4 on 2021-01-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0005_auto_20210129_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['-difficulty', 'category']},
        ),
    ]
