# Generated by Django 3.1.4 on 2021-01-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0006_auto_20210129_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
